# Generated by Django 5.0.1 on 2024-03-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_import_car_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit_paid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='email_sent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='fees_paid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='insurance_purchased',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rental_agreement_signed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rental_agreement_signed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
