# Generated by Django 5.0.1 on 2024-03-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0003_reservation_check_in_reservation_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='check_in_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_out_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
